Repository ChannexIO/Channex-BL, pull requests merged in 2020-01, with the labels that each got.

#7 tasks/update deps to latest versions
  .babelrc
  .circleci/config.yml
  .eslintignore
  .eslintrc
  package-lock.json
  package.json
  webpack.config.js
  yarn.lock
Labels: dependencies

#12 Bugfixes/CNX-609 tax calculator is not working
  lib/channex-bl.js
  lib/channex-bl.js.map
  src/collections/tax_sets.js
Labels: bug, ready_to_merge

#13 Tasks/CNX-611 replace circleci with github actions
  .circleci/config.yml
  .github/workflows/ci.yml
  package.json
Labels: ready_to_merge
